version: '3'
services:
  db:
    image: postgres:14-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  web:
    build: .
    image: rails_template:latest
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - db
  js:
    image: rails_template:latest
    command: yarn build --watch
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    tty: true
  css:
    image: rails_template:latest
    command: yarn build:css --watch
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    tty: true
volumes:
  db:
  bundle:
  node_modules:
