default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: x_clone_development


test:
  <<: *default
  database: x_clone_test
#
production:
  <<: *default
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
  database: x_clone_production
  username: x_clone
